### PR TITLE
Fix hight step break boots from other mods

### LINKED ISSUE #12859: Uphill step assist no longer works for all items that should provide it
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Darksteel boot can auto walk up a block

### The Reality

It cannot even i turn on step assist with this dark boot
image

### Your Proposal

Make it walk one block automatically like walking on slab

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12859

https://github.com/GTNewHorizons/AdventureBackpack2/pull/12/ accidently broke the high-step ability for other mods.

This PR mostly reverts the code by the PR linked above but keeps the fix that introduces it. On the top it now only reset the `stepHeight` when it has been adjusted and the piston boots are not equiped anymore.

Feel free to correct me here, if you have a better solution. :)

I've tested around with both, travler boots (Tinkers Construct) and piston boots. I switched between them both several times and I loose the high-step ability whenever I unequip them.

### CODE REVIEW

**Comment by Glease** [comment]
~~how about just remove the else branch completely? maybe also use a `Math.max(oldStepHeight, 1.001)`~~

No this won't work. You were right. We need a hashmap or something to keep track of how player had an increased stepHeight. Maybe IExtendedEntityProperties? I have heard about it but never used it before.

**Comment by Pilzinsel64** [comment]
I've tested a little bit around and also checked TC traveler boots...

I'm not sure what's about IExtendedEntilityProperties (still new to Minecraft modding :D), but a simple list is enough here.

Remembering the old step high isn't really possible unless you also use Math.Min() on restoring it and also adjust all other mods to do the same, I think.
What do you think? 🤔 Or do you have another idea for storing old high step values? 

Also, I've found out that TC adjusts the [step high in player tick event](https://github.com/GTNewHorizons/TinkersConstruct/blob/c0e365b99c803d89c75131ac7adc18ef73f40e69/src/main/java/tconstruct/armor/ArmorAbilities.java#L60-L67) and AB2 on living update event. I moved it to player tick event as the code only takes affect to players due the used conditions.

I pushed the other changes I've made. Can still change or revert them. :)

File: src/main/java/com/darkona/adventurebackpack/handlers/PlayerEventHandler.java [hunk 1]
```diff
@@ -51,6 +54,8 @@
  */
 public class PlayerEventHandler {
 
+    public static List<String> stepBoostedPlayers = new ArrayList<>();
```
Comment (eigenraven) [inline src/main/java/com/darkona/adventurebackpack/handlers/PlayerEventHandler.java]: This should be a HashSet

**Review by eigenraven — APPROVED** [review]
