### PR TITLE
Fix Hose Milking Exploit

### LINKED ISSUE #16102: Instant Infinite Milk From Single Cow With Adventure Backpack and Hose
### Your GTNH Discord Username

coldfission

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Tried milking a cow using the Adventure Backpack and Hose. I expected to get 1000mb of milk in the internal tank.

### The Reality

1000mb of milk was placed into the internal tank but the cow was not marked as milked. This allows you to keep extracting milk from the same cow.

### Your Proposal

Milking a cow with the hose should start the timer preventing you from gathering milk again like a bucket does.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Quarri6343**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16102

see: https://github.com/GTNewHorizons/HungerOverhaul/blob/master/src/main/java/iguanaman/hungeroverhaul/util/IguanaEventHook.java#L346-L353

### CODE REVIEW

File: src/main/java/com/darkona/adventurebackpack/util/HungerOverhaulUtils.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+            readMilkedTimeout();
+        }
+    }
+
+    private static void readMilkedTimeout() {
+        if (Utils.inClient()) {
+            try {
+                Class<?> iguanaConfigClass = Class.forName("iguanaman.hungeroverhaul.config.IguanaConfig");
+                Field milkedTimeoutField = iguanaConfigClass.getDeclaredField("milkedTimeout");
+                milkedTimeout = milkedTimeoutField.getInt(null);
```
Comment (OneEyeMaker) [inline src/main/java/com/darkona/adventurebackpack/util/HungerOverhaulUtils.java:24]: You can access this field directly, since one is public.
To accomplish that, add HungerOverhaul as *optional* dependency (by adding next line in `dependencies.gradle`):
```
compileOnly('curse.maven:hunger-overhaul-224476:2332505') { transitive = false }
```

Comment (Quarri6343) [reply src/main/java/com/darkona/adventurebackpack/util/HungerOverhaulUtils.java:24]: I added it as dependency at the first time, however I found this mod uses reflection to access every other mods so I just followed that

see:
https://github.com/GTNewHorizons/AdventureBackpack2/blob/master/src/main/java/com/darkona/adventurebackpack/util/GregtechUtils.java
https://github.com/GTNewHorizons/AdventureBackpack2/blob/master/src/main/java/com/darkona/adventurebackpack/util/ThaumcraftUtils.java

**Review by OneEyeMaker — APPROVED** [review]
